// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EraseSyncTime(arg1) {
  return window['go']['main']['App']['EraseSyncTime'](arg1);
}

export function ExecuteSyncs() {
  return window['go']['main']['App']['ExecuteSyncs']();
}

export function GetClosestSyncTime() {
  return window['go']['main']['App']['GetClosestSyncTime']();
}

export function SetSyncTime(arg1) {
  return window['go']['main']['App']['SetSyncTime'](arg1);
}
