// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function EraseSyncTime(arg1:number):Promise<void>;

export function ExecuteSyncs():Promise<void>;

export function GetClosestSyncTime():Promise<main.SyncTime|boolean>;

export function SetSyncTime(arg1:main.SyncTime):Promise<void>;
